newsletter_send:
  url: /newsletter/send
  params: { module: newsletter, action: send }

newsletter_nodefault:
  url: /newsletter/*
  params: { module: default, action: error }

# vim: et fenc=utf-8 sts=2 sw=2 ts=2
